### ISSUE TITLE
Add the ability to send data to multiple backends concurrently

### ISSUE THREAD

**Issue by zitroij** [sysflow-telemetry/sysflow#10]
**Indicate project**
exporter

**Describe the feature you'd like**
Allow the exporter to send the telemetry to multiple backends concurrently.  Provide a configuration for the exporter to configure the pipes it will use to send the telemetry and have the exporter act as a multiplexer.

**Comment by terylt** [comment]
Thanks for the feedback!

This is a great idea.   Do you have any particular backends you'd like to see supported by the exporter?

**Comment by zitroij** [comment]
@terylt I think if we continue with the Object storage and add Kafka and/or webhook will make it complete.  I was thinking of adding those 2 as separate issues associated with this one.
