### ISSUE TITLE
Missing File in Documentation

### ISSUE THREAD

**Issue by ysaquib** [sysflow-telemetry/sysflow#104]
**Indicate project**
documentation

**Describe the bug**
Link to elastic search [explicit mapping](https://sysflow.readthedocs.io/en/latest/resources/mappings/ecs_mapping.json) returns 404 error.

**To reproduce**
1. Click [this link](https://sysflow.readthedocs.io/en/latest/processor.html#elasticsearch)
2. Navigate to bottom of Elastic Search section
3. Click on the explicit mapping link (same url as above)

**Expected behavior**
Leads to a json file with explicit mapping

**Comment by araujof** [comment]
Fixed: https://github.com/sysflow-telemetry/sf-processor/pull/53
