### ISSUE TITLE
[Helm chart] driverType is not a method but has arguments

### ISSUE THREAD

**Issue by Marcondiro** [sysflow-telemetry/sysflow#113]
Hello,
while deploying the helm chart this error is returned:
`daemonset.yaml:267:22: executing "..." at <.Values.sfcollector.driverType>: driverType is not a method but has arguments`

**Comment by Marcondiro** [comment]
This PR fixes this issue https://github.com/sysflow-telemetry/sf-deployments/pull/33#issue-1940252964

**Comment by araujof** [comment]
Thanks for the fix, @Marcondiro! 
I have just merged it. It will ship in [0.6.0](https://github.com/orgs/sysflow-telemetry/projects/2).
