### ISSUE TITLE
Sysporter intermittently segfaults on CentOS 7

### ISSUE THREAD

**Issue by tangojulietlimalima** [sysflow-telemetry/sysflow#58]
sf-collector (sysporter) will intermittently crash on a CentOS 7 system built from source

From console:

[root@ip-XX-XX-XX-XX sysflow]# jobs
[1]+  Running                 /usr/local/sysflow/bin/sysporter -d -G 900 -w /var/lib/sysflow/sf-collector -e ip-XX-XX-XX-XX &  (wd: /home/XXXXX)
[root@ip-XX-XX-XX-XX sysflow]# E0406 01:21:15.309887 32711 networkflowprocessor.cpp:321] Cannot find Netflow Object in data flow set. Deleting. This should not happen
[root@ip-XX-XX-XX-XX sysflow]#
[1]+  Segmentation fault      /usr/local/sysflow/bin/sysporter -d -G 900 -w /var/lib/sysflow/sf-collector -e ip-XX-XX-XX-XX  (wd: /home/XXXXX)
(wd now: /var/lib/sysflow)
[root@ip-XX-XX-XX-XX sysflow]#

Expected behavior is the sysporter process does not crash. We have sysporter (sf-collector) operating on an Ubuntu system that has been running reliably for over two weeks.

Additional information captured in syslog:

Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: adding new consumer ffff88820d434000
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: initializing ring buffer for CPU 0
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: CPU buffer initialized, size=8388608
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: initializing ring buffer for CPU 1
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: CPU buffer initialized, size=8388608
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: initializing ring buffer for CPU 2
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: CPU buffer initialized, size=8388608
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: initializing ring buffer for CPU 3
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: CPU buffer initialized, size=8388608
Apr  5 18:35:08 ip-XX-XX-XX-XX kernel: sysdig_probe: starting capture
[...]
Apr  6 01:21:15 ip-XX-XX-XX-XX kernel: traps: sysporter[32711] general protection ip:7f942caa73a4 sp:7fffa187ed80 error:0 in libc-2.26.so[7f942ca29000+1a1000]
Apr  6 01:21:15 ip-XX-XX-XX-XX kernel: sysdig_probe: deallocating consumer ffff88820d434000
Apr  6 01:21:15 ip-XX-XX-XX-XX kernel: sysdig_probe: no more consumers, stopping capture

Environment:
 - OS: Amazon Linux release 2 (Karoo), 4.14.225-168.357.amzn2.x86_64
 - SysFlow version: v0.2.2
 - Command line arguments and filters: See above 
 - Configurations: Using sysdig.x86_64, 0.27.1-1
 - Container orchestration framework and version: Not applicable
 - Container runtime: Not applicable

Additional context:

sysprint will also error on malformed collector file during abrupt termination. It is assumed the collector file is in an inconsistent state following the segfault.

There is an open sysdig issue involving CentOS 7 and segmentation faults. It is unclear if this is related.

sysdig segfaults on CentOS 7 #1445:
https://github.com/draios/sysdig/issues/1445

**Comment by terylt** [comment]
I have been able to reproduce this issue, and have run through valgrind to detect any memory issues in the sysporter code. This has found some memory issues which were fixed, but which don't fix the crash.   What we have found is that sysporter runs fine without crashing if run inside the provided docker container.  I believe compiling with g++ 8.x rather than 7.x will likely fix the issue but I need to verify that.  Right now the workaround is to run the sysporter using the docker image.
