### ISSUE TITLE
Clarify and streamline engine modes and rule actions in sf-processor

### ISSUE THREAD

**Issue by axeltanner** [sysflow-telemetry/sysflow#71]
Project: sf-processor

Sf-processor provides two options to control rule-driven filtering, record tagging and alert generation. The first parameter is the policy engine mode that is set in the processor pipeline specification. The second parameter is the rule action that can be set individually for each each rule.

Currently it is not straight forward and obvious what mode/actions exactly do and in what combination they can be used. Additionally, some current settings, like the `alert` action tag are not actively doing anything.

Desired is an approach that is ideally more intuitive and streamlined without redundancies.

The past and proposed functionality is tracked in https://github.com/sysflow-telemetry/sysflow/wiki/Processor-Modes-and-Rule-Actions
Discussion around this can take place in this issue.

**Comment by axeltanner** [comment]
Wrt to the term "filter": in the context of sf-collector, a filter statement like ```FILTER="container.name!=sf-collector and container.name!=sf-exporter"``` lets everything through that matches the rule.
Inversely here filtering means that records that are matched by rules are blocked.
Of course it is different context (sf-collector vs sf-processor), still, if this could be avoided (probably through suitable naming?), it would be good imho.

**Comment by axeltanner** [comment]
All proposed modes do 'filtering' as currently described, though I am not sure how I would specify filtering rules as opposed to alerting rules?

**Comment by axeltanner** [comment]
Additionally, in the current proposal there is `alert` and `tag` both in modes and actions, essentially doing the same thing?
That seems confusing to me - and what would happen if these would be 'conflicting', ie have mode `alert` of the engine but on some rules `tag`?

**Comment by axeltanner** [comment]
Maybe in the end my question still is: do we need the mode? Or could everything be done as rule-specific actions? That could possibly include also an action `filter` (which would mean block stuff matching this rule).

Alternatively, as Teryl mentioned I think, we could have specific lists of rules, one for blocking/filtering, for alerting, for hashing or what other things might come around - in that case neither modes nor actions would be required.

**Comment by san-zrl** [comment]
Specifying filtering rules: Use a policy file that only contains

```yaml
- filter
- filter
- ...
```

**Comment by san-zrl** [comment]
Re: `alert` and `tag` in mode and action: The rule action overrides the policy mode. The mode just sets the default. With different policy modes one could use the same policies file (if is does not specify any override actions) in different ways.

**Comment by san-zrl** [comment]
And yes, I agree, the different semantics of collector filter and processor filter is mind-boggling.

**Comment by axeltanner** [comment]
> Specifying filtering rules: Use a policy file that only contains
> 
> ```yaml
> - filter
> - filter
> - ...
> ```

Ah, yes, agreed - the given example at https://sysflow.readthedocs.io/en/latest/processor.html though shows exactly the positive/negative dichotomy of 'filter'

**Comment by axeltanner** [comment]
> Re: `alert` and `tag` in mode and action: The rule action overrides the policy mode. The mode just sets the default. With different policy modes one could use the same policies file (if is does not specify any override actions) in different ways.

Ok - that could be done.

It actually might be mostly about the wordings - but I fail to have a better set of names at the moment :-(

**Comment by san-zrl** [comment]
Just to keep up the discussion: I can see two weaknesses in my proposal:
(a) it's too complicated, and
(b) filter conditions are still defined in a way that is just opposite the filter condition of the collector.

I'd like to start with (b). I can see the reasoning behind the current design. The way filter conditions currently work, we only have to evaluate filters up to the first match and drop the record. Could we just turn around this behavior and let the current record pass when we hit the first matching filter?

W.r.t (a), I can see a more radical approach. We could drop the policy mode and the rule actions altogether. Rules are always processed after the filters (if there are filters, of course). If a rule matches, the action would be determined by inspecting the "actionable" rule keys. If `tags` were specified, we add them as an attribute to the record (likewise for `severity`). If `hash: <algorithm>+` was specified, we also compute the hash value according to these algorithms and put it into the record. Rules without the "actionable" keys could work like filters.

**Comment by araujof** [comment]
> I'd like to start with (b). I can see the reasoning behind the current design. The way filter conditions currently work, we only have to evaluate filters up to the first match and drop the record. Could we just turn around this behavior and let the current record pass when we hit the first matching filter?

This would turn filters into white listings rules. This is essentially what alert mode does with the rules. I believe we added the ability to filter out (black list) so that we could combine both (white listing) alert rules while filtering out specific records (black listing) that weren't security-relevant. Think about them as "pre-filters", as they are evaluated before the rules. 
 
> W.r.t (a), I can see a more radical approach. We could drop the policy mode and the rule actions altogether. Rules are always processed after the filters (if there are filters, of course). If a rule matches, the action would be determined by inspecting the "actionable" rule keys. If `tags` were specified, we add them as an attribute to the record (likewise for `severity`). If `hash: <algorithm>+` was specified, we also compute the hash value according to these algorithms and put it into the record. Rules without the "actionable" keys could work like filters.

I think that we can't have tag and alert actions in the same policy set because alerting works as a white list (only records matching at least one alert rule is sent downstream).

Overall, I'm leaning towards the following proposal: 

* define two `modes` in the policy engine: alert, tag (default)
* make the `action` term in the rule syntax optional, and use it for defining pluggable actions that should be executed when specific rules match (e.g., compute the hash of a process after a process exec is detected). So, one action we can already support is `hash`. In the future, we could look into other types of actions.

Thougths?

**Comment by san-zrl** [comment]
> define two `modes` in the policy engine: alert, tag (default)

Do you mean that in `tag` mode the policy engine will only enrich an event with the contents of the rule's `tags` attribute if the rule condition matches? And in `alert` mode it would also append the `policies` field with name and description of the rule?

**Comment by terylt** [comment]
-filter could be made to be semantically similar to the collector and we could just use the negation to remove things...  The difference is that a filter rule could simply pass the raw sysflow file to the next stage, where alert can create an actual alert with a description, etc.     We use filter mainly to pair down events that are being sent to something like SIEM, that don't want to use the edge as a "rules engine" persay.  

Would be cool to make actions kind of like user defined functions, which could be extended.  For now, we could just support a set of core actions.

Not sure if we really need a tag and an alert mode.  Could just use the -filter, and -rule syntax, and maybe both could support an action.   The action could be a user defined function, if invoked on -filter, it would output a tagged sysflow.  if invoked on -rule it could output an alert with a tagged enrichment.   Don't know that tagging needs to be treated differently from any other action.  

The other question would just be if we supported both filters and rules, how do we determine priority?  Would priority be based on the order of the rules?  Maybe to enforce priority across multiple yamls, you could put a number in front of the yaml, like they do in system inits in Linux to determine start properties.  I think audit rules also do this.

**Comment by araujof** [comment]
> > define two `modes` in the policy engine: alert, tag (default)
> 
> Do you mean that in `tag` mode the policy engine will only enrich an event with the contents of the rule's `tags` attribute if the rule condition matches? And in `alert` mode it would also append the `policies` field with name and description of the rule?

Yes! :)

**Comment by axeltanner** [comment]
Proposal: clear write-up of the current ideas (I think there are like 2 around, Fred's view & Teryl's view), using a list of prototypical events to cover the different cases.
At first glance I see:
- event to filter = not pass on
- event to pass on unchanged
- event to create alert
- event to enrich (if that is different from previous)
- event to include hash (or potential future other actions)
others?

**Comment by san-zrl** [comment]
## Modes and Rules

Here's my promised write-up on modes and rules.

Given the above cases it seems that we don't need rules action anymore which greatly simplifies things. It is sufficient to define 3 policy engine modes `alert`, `tag` and `filter` that control the application of rules to cover all possible cases. 

Let me show by example how this could work. Suppose we have a sysflow trace consiting of 4 events of different types:

```
{ "type": "PE", ...}
{ "type": "FE", ...}
{ "type": "FF", ...}
{ "type": "NF", ...}
```

We have one rule to detect phony network flows which matches exactly one event from the sample trace.

```
- rule: NF detected
  desc: sample rule
  condition: sf.type = NF
  tags: [mitre:Txxxx]
  priority: low
```

Note that there's no action defined for this rule. The effect of applying this rule to our sample trace depends on the policy engine mode. 

### Mode `tag` - Enrich matching events and pass on all others

The tagging mode is the default mode. In this mode, only matching events will be tagged. All other events will be passed on unchanged. Tagging does not block events from the trace, there will be as many events in the output channel as there were events in the input channel.

When applying our rule, only one event matches. Only this event will be enriched with the tags specified; the rest passes unchanged. The output would look like this:

```
{ "type": "PE", ...}
{ "type": "FE", ...}
{ "type": "FF", ...}
{ "type": "NF", ..., "policies":[{"id":"NF detected","desc":"sample rule","tags":["mitre:Txxxx"]}]}}
```

Note that the priority is ignored in tagging mode.

### Mode `alert` - Enrich matching events and suppress all others

In alert mode, the behavior is slightly different. Matching events will be enriched as before but non-matching events will be blocked. This reduces the number of events to only those that matched one or mode rules.

The resulting events are called *alerts* and have a priority as specified in the rule. Only alerts will be passed on. In our example we would have one *alert*

```
{ "type": "NF", ..., "policies":[{"id":"NF detected","desc":"sample rule",priority":0,"tags":["mitre:Txxxx"]}]}}
```

### Mode `filter` - Block non-matching events

The fiter mode finally blocks all events that do not match any rule. As opposed to the two other modes, matching events will be passed on unchanged. Filter mode generate as many output records as alert mode. The difference is that they are passed on as is, which effectively turns rules into filters.

```
{ "type": "NF" ...}
```

### Hashes

Hashes would be treated just like tags and would only be computed in `tag` or `alert` mode for the process executable of the matching event. Hash generation could be enabled via a `hash` tag in the rule that specifies the hash algorithm. For MD5 hashes, our rule would look like this 

```
- rule: NF detected
  desc: sample rule
  condition: sf.type = NF
  tags: [mitre:Txxxx]
  priority: low
  hash: [md5]
```

**Comment by axeltanner** [comment]
Tentative summary of the last proposal:
| Desired action  | engine mode | rule action | rule example | result | comments |
| ------------- | ------------- | - | - | - | - |
| passthrough | filter | na | - rule: ...<br>desc: ...<br>condition: ...<br>tags: [...]<br>priority: ... | events not fitting any filter rule will be dropped | |
| enrich/tag | tag | na | like above | adds tag to events matching condition; passthrough for all other events | |
| alert | alert | na | like above | adds tag to events matching conditions; blocks all non-matching events | results in → alerts |
| hash | tag or alert | na |  - rule: ...<br>desc: ...<br>condition: ...<br>tags: [...]<br>priority: ...<br>hash: [md5] | acts as tag/alert would do, just adding requested hash for proc.exe | |
| block | ? | na | | | |

**Comment by axeltanner** [comment]
Questions wrt this approach
- how about other possible enrichments?
- how about what to hash, eg the file not the proc.exe?
- hard to block specific things (given this direction of filter - which though is correct in the sense of consistent with the sf-collector filter)
- more focus on this keyword idea? but then this goes into the direction of actions again?

**Comment by san-zrl** [comment]
> how about what to hash, eg the file not the proc.exe?

God point. I always I thought this is proc.exe since file is not always present.

> hard to block specific things (given this direction of filter - which though is correct in the sense of consistent with the sf-collector filter)

True. What about a mode `block` as listed above which behaves like `filter` but toggles the semantics to "events matsch any rule will be dropped"?

**Comment by axeltanner** [comment]
Summary of current most recent discussion:
- keep modes & actions - but they should be orthogonal to each other
- **modes** - set per processor engine
  - filter: only matching events will go through, everything else is blocked
  - tag: matching events will be handled and enriched (actions will be executed), other events will go through w/o change
  - alert: matching events will be handled and enriched (actions will be executed), other events will be blocked
- **actions** - set per rule
  - there would be built-in actions (like hash), but open for user-defined actions
  - imagine like 'user-defined stored procedures'
  - implemented as plug-ins
  - as some actions (like fetching additional information) might take longer, handling should not be inline/blocking the pipeline
  - this requires a plugin interface & stack/channel for the async requests
  - it should be possible to have one event trigger an immediate reaction (like an alert) and in addition have a (delayed since async) additional reaction for that event - needs event duplication in some form

Other considerations:
- keep the `prefilter` option for the rule to select specific event types (important for performance) 
- blocking specific events is possible via a negated match in a filter-mode engine

**Comment by axeltanner** [comment]
Summary of plans from discussion 2021-10-05, updating from the previous description:

- keep modes & actions - orthogonal to each other
- **modes** - set per processor engine
    - `filter`: only matching events will go through, everything else is blocked, no actions will be handled
    - `enrich`: matching events will be handled and enriched (actions will be executed), other events will go through w/o change
    - `alert`: matching events will be handled and enriched (actions will be executed), other events will be blocked
- **actions** - set per rule
    - there would be built-in actions (like `hash`), but open for user-defined actions
    - no `alert` action required anymore
    - imagine like 'user-defined stored procedures'
    - implemented as plug-ins
    - as some actions (like fetching additional information) might take longer, handling should not be inline/blocking the pipeline
    - this requires a plugin interface & stack/channel for the async requests
    - it should be possible to have one event trigger an immediate reaction (like an alert) and in addition have a (delayed since async) additional reaction for that event - needs event duplication in some form

enrichment 
- here defined as enriching with the rule metadata, which includes tags
- keep the schema of the data as stable as possible
- additional information can be added, but encoded as `key:value` pairs added to the `tags` field (like `mitre:T1110` is now)

Other considerations:

- keep the `prefilter` option for the rule to select specific event types (important for performance)
- blocking specific events is possible via a negated match in a filter-mode engine

**Comment by san-zrl** [comment]
Default mode will be `enrich` since this is the only non-blocking mode and works without a policy definition. Thus, the simplest working engine configuration doesn't specify mode or policy file and behaves like the old `bypass` mode.

**Comment by san-zrl** [comment]
Submitted [PR #38](https://github.com/sysflow-telemetry/sf-processor/pull/38) as a first attempt to resolve this issue.

**Comment by san-zrl** [comment]
I updated[ PR #38](https://github.com/sysflow-telemetry/sf-processor/pull/38). See my latest comment there for the list of added features.

**Comment by araujof** [comment]
Remaining TODOs to close this issue:
[ ] Documenting new policy engine modes 
[ ] Add backwards compatibility to `filter` rule
