### ISSUE TITLE
Add support for Pod object to SysFlow

### ISSUE THREAD

**Issue by terylt** [sysflow-telemetry/sysflow#8]
**Indicate project**
collector, sysflow specification

**Describe the feature you'd like**
Currently, SysFlow does not store information about pod structures such as kubernetes.   This is valuable information for analytics and could be added to the specification. 
**Describe alternatives you've considered**
The pod could be added as an additional entity object or simply as an ID to he container object.  We must think about what information we'd like to store about the pod.

**Comment by araujof** [comment]
Upstreamed in 0.5.0
