### ISSUE TITLE
Deploying SysFlow on OpenShift 4.10.x

### ISSUE THREAD

**Issue by egrol** [sysflow-telemetry/sysflow#92]
**Indicate project**
i.e. collector, exporter, deployment, etc.

Full Deployment of SysFlow to an OpenShift Cluster 4.10.25 in order to aggregate all events network/process/file/execution etc.

**Describe the bug**

Attempts were made to deploy SysFlow using the OpenShift Operator Hub. The Operator installed successfully but the deployment of the SysFlow Agent fails due to these errors:

Failed
api-server resource not found installing CustomResourceDefinition sysflowagents.sysflow.ibm.com: GroupVersionKind apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition not found on the cluster. This API may have been deprecated and removed, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/ for more information.

1. Setup OpenShift 4.10.25
2. Create sysflow project
3. Install sysflow operator into sysflow project
4. Unable to execute agent creation due to error

**Screenshots**

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/28523014/192225187-06a09821-001a-41a5-b9f6-b5b11e09849c.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/28523014/192225220-13e7a18b-15f8-4287-ba28-38ea218e4d33.png">

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/28523014/192225055-ce8bd253-5abc-41ec-878d-0915c6ba41f0.png">

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/28523014/192225124-70ec6c03-8ec9-473d-a0bc-1ed1ad19ec52.png">

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/28523014/192225269-720069d4-e912-4df0-b4ea-785b5fb6d8ad.png">

**Environment (please complete the following information):**

 - OS: Red Hat CoreOS
 - SysFlow version: main using IBM operator 1.0 for SysFlow
 - Command line arguments and filters (if applicable): NA
 - Configurations (if applicable): Attempting to integrate SysFlow with QRadar SIEM (and use OOTB DSM for SysFlow)
 - Container orchestration framework and version (if applicable): OpenShift
 - Container runtime (if applicable): CRI-O

**Additional context**

The objective is to install and configure the SysFlow agent to send through ALL respective event types collected to QRadar SIEM. Is it possible to detail if this is possible without having to S3 buckets to aggregate event data? There is a QRadar SIEM DSM out-of-the-box module in which we will use to normalize and use the event data (for offences).

**Files**

NA

**Comment by araujof** [comment]
Thanks for reporting this issue, @egrol!

I see you are deploying with IBM Security's operator. This operator is no longer maintained (it uses an old version of SysFlow). We maintain a community helm chart that should work in your environment. We have a ticket open with the QRadar team to update the QRadar knowledge base. In the meanwhile, this is what you would need to do:

1. Install the DSM update for your QRadar instance ([7.3](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=IBM%20Security&product=ibm/Other+software/IBM+Security+QRadar+SIEM&release=All&platform=All&function=fixId&fixids=7.3.0-QRADAR-DSM-SysFlow-7.3-20220520132628.noarch.rpm&includeSupersedes=0&source=fc), [7.4](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=IBM%20Security&product=ibm/Other+software/IBM+Security+QRadar+SIEM&release=All&platform=All&function=fixId&fixids=7.4.0-QRADAR-DSM-SysFlow-7.4-20220520132129.noarch.rpm&includeSupersedes=0&source=fc), [7.5](http://www.ibm.com/support/fixcentral/swg/quickorder?parent=IBM%20Security&product=ibm/Other+software/IBM+Security+QRadar+SIEM&release=All&platform=All&function=fixId&fixids=7.5.0-QRADAR-DSM-SysFlow-7.5-20220520132646.noarch.rpm&includeSupersedes=0&source=fc))
2. Use Helm (v3) to install the SysFlow agent on your environment with the Helm charts from [sf-deployments](https://github.com/sysflow-telemetry/sf-deployments/tree/0.4.4/helm). This will install SysFlow 0.4.4. 

Please let me know if this works for you.

**Comment by araujof** [comment]
Also, to your question on whether it's possible to deploy SysFlow without the S3 integration, the answer is yes. It's documented in the README [here](https://github.com/sysflow-telemetry/sf-deployments/tree/master/helm#deploy-sysflow).
